# Generated by Django 6.1.1 on 2026-10-03 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='users',
        ),
    ]
