# Generated by Django 5.2.17 on 2026-10-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
    ]
