# Generated by Django 6.1.1 on 2026-10-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
    ]
