# Generated by Django 6.1.1 on 2026-10-03 06:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid5, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
